exports.DOWNLOAD_IMAGE_OFFLINE = 'DOWNLOAD_IMAGE_OFFLINE';
exports.DOWNLOAD_IMAGE_OFFLINE_SUCCESS = 'DOWNLOAD_IMAGE_OFFLINE_SUCCESS';
exports.DOWNLOAD_IMAGE_OFFLINE_FAILED = 'DOWNLOAD_IMAGE_OFFLINE_FAILED';
exports.DOWNLOAD_IMAGE_OFFLINE_NETWORK_ERROR = 'DOWNLOAD_IMAGE_OFFLINE_NETWORK_ERROR';
exports.DOWNLOAD_IMAGE_OFFLINE_TIMEOUT = 'DOWNLOAD_IMAGE_OFFLINE_TIMEOUT';